import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { LayoutComponent } from './shared/components/layout.component';
import { AuthService } from './core/services/auth.service';
import { StorageService } from './core/services/storage.service';
import { Appointment, Doctor, MedicalRecord, Medication, Patient, Prescription, TestOrder, TestResult, User } from './core/models/models';

@Component({selector:'cc-portal',standalone:true,imports:[CommonModule,FormsModule,ReactiveFormsModule,LayoutComponent],template:`
<cc-layout [items]="menu">
<div class="page">
  @if(toast){<div class="toast">✓ {{toast}}</div>}
  @if(page==='dashboard'){<ng-container [ngTemplateOutlet]="dashboardTpl"></ng-container>}
  @if(page==='profile' && role==='patient'){<ng-container [ngTemplateOutlet]="profileTpl"></ng-container>}
  @if(page==='appointments'){<ng-container [ngTemplateOutlet]="appointmentsTpl"></ng-container>}
  @if(page==='patients' && role==='doctor'){<ng-container [ngTemplateOutlet]="doctorPatientsTpl"></ng-container>}
  @if(page==='consultation' && role==='doctor'){<ng-container [ngTemplateOutlet]="consultationTpl"></ng-container>}
  @if(page==='prescriptions'){<ng-container [ngTemplateOutlet]="prescriptionsTpl"></ng-container>}
  @if(page==='cpoe' && role==='doctor'){<ng-container [ngTemplateOutlet]="cpoeTpl"></ng-container>}
  @if(page==='test-results'){<ng-container [ngTemplateOutlet]="resultsTpl"></ng-container>}
  @if(page==='medical-records'){<ng-container [ngTemplateOutlet]="recordsTpl"></ng-container>}
  @if(role==='admin' && ['patients','doctors','users'].includes(page)){<ng-container [ngTemplateOutlet]="adminUsersTpl"></ng-container>}
  @if(role==='admin' && page==='system'){<ng-container [ngTemplateOutlet]="systemTpl"></ng-container>}
</div>
</cc-layout>

<ng-template #dashboardTpl>
<section class="page-head"><div><span class="eyebrow">CARECONNECT · {{role|titlecase}}</span><h1>Welcome back, {{auth.user()?.name}}</h1><p>Here's an overview of your healthcare information.</p></div></section>
<div class="stats">@for(s of stats;track s.label){<div class="stat-card"><span>{{s.icon}}</span><small>{{s.label}}</small><strong>{{s.value}}</strong></div>}</div>
@if(role==='patient'){<div class="two-col"><section class="card"><div class="card-head"><h2>Upcoming Appointment</h2><a (click)="go('appointments')">View all</a></div>@if(myAppointments.length){@for(a of myAppointments.slice(0,1);track a.id){<div class="appointment-highlight"><b>{{a.doctorName}}</b><span>{{a.specialization}}</span><div>{{a.date}} · {{a.time}}</div><em>{{a.status}}</em></div>}}@else{<div class="empty">No upcoming appointments.</div>}</section><section class="card"><div class="card-head"><h2>Recent Prescriptions</h2><a (click)="go('prescriptions')">View all</a></div>@for(rx of myPrescriptions.slice(0,3);track rx.id){<div class="list-row"><div><b>{{rx.medicines[0]?.name}}</b><small>{{rx.medicines[0]?.dosage}} · {{rx.medicines[0]?.frequency}}</small></div><span>{{rx.date}}</span></div>}@empty{<div class="empty">No prescriptions yet.</div>}</section></div>}
@if(role==='doctor'){<div class="card"><div class="card-head"><h2>Today's Appointments</h2><a (click)="go('appointments')">Manage</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th><th></th></tr></thead><tbody>@for(a of doctorAppointments.slice(0,6);track a.id){<tr><td><b>{{a.patientName}}</b></td><td>{{a.date}}</td><td>{{a.time}}</td><td>{{a.reason}}</td><td><span class="badge">{{a.status}}</span></td><td><button class="btn small" (click)="openConsult(a)">Open</button></td></tr>}@empty{<tr><td colspan="6" class="empty">No appointments.</td></tr>}</tbody></table></div></div>}
@if(role==='admin'){<div class="card"><div class="card-head"><h2>System Snapshot</h2><a (click)="go('users')">Manage users</a></div><div class="quick-grid">@for(x of adminCards;track x.label){<div><strong>{{x.value}}</strong><span>{{x.label}}</span></div>}</div></div>}
</ng-template>

<ng-template #profileTpl><section class="page-head"><div><span class="eyebrow">PATIENT PORTAL</span><h1>My Profile</h1><p>Keep your personal and medical information up to date.</p></div></section><section class="card"><form [formGroup]="profileForm" (ngSubmit)="saveProfile()" class="form-grid"><label>Full Name<input class="input" formControlName="name"></label><label>Date of Birth<input class="input" type="date" formControlName="dob"></label><label>Gender<select class="input" formControlName="gender"><option>Male</option><option>Female</option><option>Other</option></select></label><label>Phone<input class="input" formControlName="phone"></label><label>Email<input class="input" formControlName="email"></label><label>Emergency Contact<input class="input" formControlName="emergency"></label><label>Blood Group<select class="input" formControlName="bloodGroup"><option>O+</option><option>A+</option><option>B+</option><option>AB+</option><option>O-</option><option>A-</option><option>B-</option><option>AB-</option></select></label><label>Patient ID<input class="input" [value]="currentPatient()?.id" disabled></label><label class="span-2">Address<textarea class="input" rows="2" formControlName="address"></textarea></label><label class="span-2">Medical History<textarea class="input" rows="3" formControlName="medicalHistory"></textarea></label><div class="span-2"><button class="btn primary" [disabled]="profileForm.invalid">Save Profile</button></div></form></section></ng-template>

<ng-template #appointmentsTpl><section class="page-head"><div><span class="eyebrow">APPOINTMENT MANAGEMENT</span><h1>{{role==='patient'?'My Appointments':'Appointments'}}</h1><p>{{role==='patient'?'Book a new visit or review previous appointments.':'Open appointments to complete consultations.'}}</p></div></section>@if(role==='patient'){<div class="two-col"><section class="card"><h2>Book New Appointment</h2><form [formGroup]="appointmentForm" (ngSubmit)="bookAppointment()" class="stack"><label>Doctor<select class="input" formControlName="doctorId">@for(d of doctors;track d.id){<option [value]="d.id">{{d.name}} · {{d.specialization}}</option>}</select></label><label>Specialization<input class="input" [value]="selectedDoctor()?.specialization||''" disabled></label><label>Date<input class="input" type="date" formControlName="date"></label><label>Time<input class="input" type="time" formControlName="time"></label><label>Reason for Visit<textarea class="input" rows="3" formControlName="reason"></textarea></label><button class="btn primary" [disabled]="appointmentForm.invalid">Book Appointment</button></form></section><section class="card"><h2>Appointment History</h2><div class="stack gap">@for(a of myAppointments;track a.id){<div class="record-row"><div><b>{{a.doctorName}}</b><small>{{a.specialization}} · {{a.date}} · {{a.time}}</small><small>{{a.reason}}</small></div><span class="badge">{{a.status}}</span></div>}@empty{<div class="empty">No appointments found.</div>}</div></section></div>}@else if(role==='doctor'){<section class="card table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>@for(a of doctorAppointments;track a.id){<tr><td>{{a.patientName}}</td><td>{{a.date}}</td><td>{{a.time}}</td><td>{{a.reason}}</td><td><span class="badge">{{a.status}}</span></td><td><button class="btn small" (click)="openConsult(a)">Open Consultation</button></td></tr>}@empty{<tr><td colspan="6" class="empty">No appointments found.</td></tr>}</tbody></table></section>}@else{<section class="card table-wrap"><table class="table"><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th></tr></thead><tbody>@for(a of appointments;track a.id){<tr><td>{{a.patientName}}</td><td>{{a.doctorName}}</td><td>{{a.date}}</td><td>{{a.time}}</td><td>{{a.reason}}</td><td><span class="badge">{{a.status}}</span></td></tr>}@empty{<tr><td colspan="6" class="empty">No appointments found.</td></tr>}</tbody></table></section>}</ng-template>

<ng-template #doctorPatientsTpl><section class="page-head"><div><span class="eyebrow">DOCTOR PORTAL</span><h1>Patients</h1><p>Search patients and open their healthcare history.</p></div></section><section class="card"><input class="input search" placeholder="Search by name, email or phone" [(ngModel)]="search"><div class="table-wrap"><table class="table"><thead><tr><th>Patient ID</th><th>Name</th><th>Age</th><th>Gender</th><th>Phone</th><th>Last Visit</th><th></th></tr></thead><tbody>@for(p of filteredPatients;track p.id){<tr><td>{{p.id}}</td><td><b>{{p.name}}</b><small>{{p.email}}</small></td><td>{{age(p.dob)}}</td><td>{{p.gender}}</td><td>{{p.phone}}</td><td>{{lastVisit(p.id)}}</td><td><button class="btn small" (click)="viewPatient(p)">View</button></td></tr>}@empty{<tr><td colspan="7" class="empty">No patients match your search.</td></tr>}</tbody></table></div></section>@if(selectedPatient){<div class="modal-backdrop" (click)="selectedPatient=null"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><h2>{{selectedPatient.name}}</h2><button (click)="selectedPatient=null">×</button></div><div class="detail-grid"><div><small>Patient ID</small><b>{{selectedPatient.id}}</b></div><div><small>Age</small><b>{{age(selectedPatient.dob)}}</b></div><div><small>Blood Group</small><b>{{selectedPatient.bloodGroup}}</b></div><div><small>Phone</small><b>{{selectedPatient.phone}}</b></div><div class="span-2"><small>Medical History</small><b>{{selectedPatient.medicalHistory}}</b></div></div><div class="modal-actions"><button class="btn outline" (click)="goPatientRecords(selectedPatient)">Medical History</button><button class="btn primary" (click)="startPatientConsultation(selectedPatient)">Open Consultation</button></div></div></div>}</ng-template>

<ng-template #consultationTpl><section class="page-head"><div><span class="eyebrow">DOCTOR PORTAL</span><h1>Consultation</h1><p>Document observations, diagnosis, treatment and follow-up instructions.</p></div></section>@if(consultPatient){<section class="card"><div class="patient-banner"><div><small>Patient</small><b>{{consultPatient.name}}</b></div><div><small>Patient ID</small><b>{{consultPatient.id}}</b></div><div><small>Age</small><b>{{age(consultPatient.dob)}}</b></div><div><small>Gender</small><b>{{consultPatient.gender}}</b></div><div><small>History</small><b>{{consultPatient.medicalHistory}}</b></div></div><form [formGroup]="consultForm" (ngSubmit)="saveConsultation()" class="form-grid"><label>Symptoms<textarea class="input" rows="3" formControlName="symptoms"></textarea></label><label>Diagnosis<textarea class="input" rows="3" formControlName="diagnosis"></textarea></label><label>Observations<textarea class="input" rows="3" formControlName="observations"></textarea></label><label>Clinical Notes<textarea class="input" rows="3" formControlName="clinicalNotes"></textarea></label><label>Treatment Plan<textarea class="input" rows="3" formControlName="treatmentPlan"></textarea></label><label>Doctor Suggestions<textarea class="input" rows="3" formControlName="suggestions"></textarea></label><label>Precautions<textarea class="input" rows="3" formControlName="precautions"></textarea></label><label>Follow-up Instructions<textarea class="input" rows="3" formControlName="followUp"></textarea></label><div class="span-2"><button class="btn primary" [disabled]="consultForm.invalid">Save Consultation</button></div></form></section>}@else{<section class="card empty">Select an appointment from the Appointments page to start a consultation.</section>}</ng-template>

<ng-template #prescriptionsTpl><section class="page-head"><div><span class="eyebrow">PRESCRIPTIONS</span><h1>Prescriptions</h1><p>{{role==='doctor'?'Create prescriptions for your patients.':'Review medicines prescribed by your doctors.'}}</p></div></section>@if(role==='doctor'){<div class="two-col"><section class="card"><h2>Create Prescription</h2><label>Patient<select class="input" [(ngModel)]="rxPatientId">@for(p of patients;track p.id){<option [value]="p.id">{{p.name}} ({{p.id}})</option>}</select></label><form [formGroup]="medForm" (ngSubmit)="addMedicine()" class="stack top-gap"><label>Medicine Name<input class="input" formControlName="name"></label><div class="form-grid compact"><label>Dosage<input class="input" formControlName="dosage"></label><label>Frequency<input class="input" formControlName="frequency"></label><label>Duration<input class="input" formControlName="duration"></label><label>Instructions<input class="input" formControlName="instructions"></label><label class="span-2">Precautions<input class="input" formControlName="precautions"></label></div><button class="btn outline">+ Add Medicine</button></form>@if(cart.length){<div class="table-wrap top-gap"><table class="table"><thead><tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th></th></tr></thead><tbody>@for(m of cart;track $index){<tr><td>{{m.name}}</td><td>{{m.dosage}}</td><td>{{m.frequency}}</td><td>{{m.duration}}</td><td><button class="link danger" (click)="removeMedicine($index)">Remove</button></td></tr>}</tbody></table></div><button class="btn primary top-gap" (click)="savePrescription()">Create Prescription</button>}</section><section class="card"><h2>Saved Prescriptions</h2>@for(rx of prescriptions;track rx.id){<div class="prescription"><div class="card-head"><b>{{rx.doctorName}}</b><span>{{rx.date}}</span></div>@for(m of rx.medicines;track m.name){<div class="med-row"><b>{{m.name}}</b><span>{{m.dosage}} · {{m.frequency}} · {{m.duration}}</span><small>{{m.instructions}} · {{m.precautions}}</small></div>}</div>}@empty{<div class="empty">No prescriptions created yet.</div>}</section></div>}@else{<section class="stack gap">@for(rx of myPrescriptions;track rx.id){<article class="card prescription"><div class="card-head"><div><small>Prescribed by</small><h2>{{rx.doctorName}}</h2></div><span>{{rx.date}}</span></div>@for(m of rx.medicines;track m.name){<div class="med-row large"><b>{{m.name}}</b><span>{{m.dosage}} · {{m.frequency}} · {{m.duration}}</span><small>Instructions: {{m.instructions||'—'}}</small><small>Precautions: {{m.precautions||'—'}}</small></div>}</article>}@empty{<div class="card empty">No prescriptions available.</div>}</section>}</ng-template>

<ng-template #cpoeTpl><section class="page-head"><div><span class="eyebrow">CPOE</span><h1>Test Orders</h1><p>Create and track computerized provider orders.</p></div></section><div class="two-col"><section class="card"><h2>New Test Order</h2><form [formGroup]="orderForm" (ngSubmit)="addOrder()" class="stack"><label>Patient<select class="input" formControlName="patientId">@for(p of patients;track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label><label>Test Type<input class="input" formControlName="testType" placeholder="e.g. CBC, MRI"></label><label>Order Date<input class="input" type="date" formControlName="orderDate"></label><label>Priority<select class="input" formControlName="priority"><option>Normal</option><option>Urgent</option></select></label><label>Clinical Remarks<textarea class="input" rows="3" formControlName="remarks"></textarea></label><button class="btn primary" [disabled]="orderForm.invalid">Create Test Order</button></form></section><section class="card table-wrap"><h2>Existing Orders</h2><table class="table"><thead><tr><th>Patient</th><th>Test</th><th>Date</th><th>Priority</th><th>Status</th></tr></thead><tbody>@for(o of orders;track o.id){<tr><td>{{o.patientName}}</td><td>{{o.testType}}</td><td>{{o.orderDate}}</td><td>{{o.priority}}</td><td>{{o.status}}</td></tr>}@empty{<tr><td colspan="5" class="empty">No test orders.</td></tr>}</tbody></table></section></div></ng-template>

<ng-template #resultsTpl><section class="page-head"><div><span class="eyebrow">TEST RESULTS</span><h1>Test Results</h1><p>{{role==='doctor'?'Publish results for patients.':'View results shared by your doctors.'}}</p></div></section>@if(role==='doctor'){<section class="card"><h2>Add Test Result</h2><form [formGroup]="resultForm" (ngSubmit)="addResult()" class="form-grid"><label>Patient<select class="input" formControlName="patientId">@for(p of patients;track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label><label>Test Name<input class="input" formControlName="testName"></label><label>Test Date<input class="input" type="date" formControlName="testDate"></label><label>Status<select class="input" formControlName="status"><option>Completed</option><option>Pending Review</option></select></label><label class="span-2">Result<textarea class="input" rows="4" formControlName="result"></textarea></label><label class="span-2">Remarks<textarea class="input" rows="3" formControlName="remarks"></textarea></label><div class="span-2"><button class="btn primary" [disabled]="resultForm.invalid">Add Test Result</button></div></form></section>}<section class="card top-gap table-wrap"><table class="table"><thead><tr><th>Test</th><th>Date</th><th>Result</th><th>Doctor</th><th>Status</th><th></th></tr></thead><tbody>@for(r of visibleResults;track r.id){<tr><td><b>{{r.testName}}</b><small>{{r.patientName}}</small></td><td>{{r.testDate}}</td><td>{{r.result}}</td><td>{{r.doctor}}</td><td>{{r.status}}</td><td><button class="btn small" (click)="selectedResult=r">View</button></td></tr>}@empty{<tr><td colspan="6" class="empty">No test results available.</td></tr>}</tbody></table></section>@if(selectedResult){<div class="modal-backdrop" (click)="selectedResult=null"><div class="modal" (click)="$event.stopPropagation()"><div class="modal-head"><h2>{{selectedResult.testName}}</h2><button (click)="selectedResult=null">×</button></div><p><b>Patient:</b> {{selectedResult.patientName}}</p><p><b>Date:</b> {{selectedResult.testDate}}</p><div class="result-box">{{selectedResult.result}}</div><p><b>Remarks:</b> {{selectedResult.remarks||'—'}}</p><p><b>Doctor:</b> {{selectedResult.doctor}}</p></div></div>}</ng-template>

<ng-template #recordsTpl><section class="page-head"><div><span class="eyebrow">MEDICAL RECORDS</span><h1>Medical History</h1><p>{{role==='patient'?'Your consultation timeline.':'Consultation records across your patients.'}}</p></div></section><div class="timeline">@for(r of visibleRecords;track r.id){<article class="record-card"><div class="record-date">{{r.date}}</div><div class="card"><div class="card-head"><div><small>Doctor</small><h2>{{r.doctorName}}</h2></div><span class="badge">{{r.diagnosis}}</span></div><div class="detail-grid"><div><small>Symptoms</small><p>{{r.symptoms}}</p></div><div><small>Observations</small><p>{{r.observations}}</p></div><div><small>Treatment Plan</small><p>{{r.treatmentPlan}}</p></div><div><small>Doctor Suggestions</small><p>{{r.suggestions}}</p></div><div><small>Precautions</small><p>{{r.precautions}}</p></div><div><small>Follow-up</small><p>{{r.followUp}}</p></div></div></div></article>}@empty{<div class="card empty">No medical records available.</div>}</div></ng-template>

<ng-template #adminUsersTpl><section class="page-head"><div><span class="eyebrow">ADMINISTRATION</span><h1>{{page|titlecase}}</h1><p>{{page==='doctors'?'Create and manage doctor accounts.':'Manage users and account status.'}}</p></div></section>@if(page==='doctors'){<section class="card"><div class="card-head"><div><h2>Add Doctor</h2><p>Create a login account for a doctor.</p></div></div><form [formGroup]="doctorForm" (ngSubmit)="createDoctor()" class="form-grid"><label>Full Name<input class="input" formControlName="name" placeholder="Dr. Full Name"></label><label>Email<input class="input" type="email" formControlName="email" placeholder="doctor@example.com"></label><label>Username<input class="input" formControlName="username" placeholder="doctor username"></label><label>Phone<input class="input" formControlName="phone" placeholder="10 digit phone number"></label><label>Password<input class="input" type="password" formControlName="password" placeholder="Minimum 6 characters"></label><label>Specialization<input class="input" formControlName="specialization" placeholder="e.g. Cardiologist"></label><div class="span-2"><button class="btn primary" [disabled]="doctorForm.invalid || doctorSubmitting">{{doctorSubmitting?'Creating...':'Create Doctor Account'}}</button></div></form></section>}<section class="card table-wrap"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Role / Specialization</th><th>Status</th><th>Action</th></tr></thead><tbody>@for(u of adminList();track u.id){<tr><td>{{u.id}}</td><td>{{u.name}}</td><td>{{u.email}}</td><td>{{u.phone||'—'}}</td><td>{{u.role==='doctor'?doctorSpec(u.id):u.role|titlecase}}</td><td><span class="badge" [class.good]="u.active" [class.bad]="!u.active">{{u.active?'Active':'Inactive'}}</span></td><td><button class="btn small" (click)="toggleUser(u)">{{u.active?'Deactivate':'Activate'}}</button></td></tr>}@empty{<tr><td colspan="7" class="empty">No users found.</td></tr>}</tbody></table></section></ng-template>

<ng-template #systemTpl><section class="page-head"><div><span class="eyebrow">ADMINISTRATION</span><h1>System Management</h1><p>Current system data and account summary.</p></div></section><section class="card"><h2>Storage Summary</h2><div class="quick-grid">@for(x of adminCards;track x.label){<div><strong>{{x.value}}</strong><span>{{x.label}}</span></div>}</div></section></ng-template>
`})
export class PortalComponent {
  role=this.auth.role()!; page='dashboard'; toast=''; search=''; selectedPatient:Patient|null=null; selectedResult:TestResult|null=null; consultPatient:Patient|null=null; rxPatientId=''; cart:Medication[]=[];
  patients:Patient[]=[]; doctors:Doctor[]=[]; appointments:Appointment[]=[]; prescriptions:Prescription[]=[]; records:MedicalRecord[]=[]; orders:TestOrder[]=[]; results:TestResult[]=[];
  menu=this.buildMenu();
  profileForm=this.fb.group({name:['',Validators.required],dob:['',Validators.required],gender:['',Validators.required],phone:['',[Validators.required,Validators.pattern(/^[0-9]{10}$/)]],email:['',[Validators.required,Validators.email]],emergency:[''],bloodGroup:[''],address:[''],medicalHistory:['']});
  appointmentForm=this.fb.group({doctorId:['',Validators.required],date:['',Validators.required],time:['',Validators.required],reason:['',Validators.required]});
  consultForm=this.fb.group({symptoms:['',Validators.required],diagnosis:['',Validators.required],observations:[''],clinicalNotes:[''],treatmentPlan:[''],suggestions:[''],precautions:[''],followUp:['']});
  medForm=this.fb.group({name:['',Validators.required],dosage:['',Validators.required],frequency:['',Validators.required],duration:['',Validators.required],instructions:[''],precautions:['']});
  orderForm=this.fb.group({patientId:['',Validators.required],testType:['',Validators.required],orderDate:[this.today(),Validators.required],remarks:[''],priority:['Normal',Validators.required]});
  resultForm=this.fb.group({patientId:['',Validators.required],testName:['',Validators.required],testDate:[this.today(),Validators.required],result:['',Validators.required],remarks:[''],status:['Completed',Validators.required]});
  doctorForm=this.fb.group({name:['',[Validators.required,Validators.minLength(2)]],email:['',[Validators.required,Validators.email]],username:[''],phone:['',[Validators.pattern(/^[0-9]{10}$/)]],password:['',[Validators.required,Validators.minLength(6)]],specialization:['',[Validators.required,Validators.minLength(2)]]});
  doctorSubmitting=false;
  constructor(private route:ActivatedRoute,private router:Router,public auth:AuthService,private s:StorageService,private fb:FormBuilder){this.route.url.subscribe(parts=>{this.page=parts[0]?.path||'dashboard';this.refresh()});}
  today(){return new Date().toISOString().slice(0,10)}
  buildMenu(){if(this.role==='patient')return[{label:'Dashboard',path:'/patient/dashboard',icon:'⌂'},{label:'My Profile',path:'/patient/profile',icon:'◉'},{label:'Appointments',path:'/patient/appointments',icon:'▣'},{label:'Medical Records',path:'/patient/medical-records',icon:'▤'},{label:'Prescriptions',path:'/patient/prescriptions',icon:'Rx'},{label:'Test Results',path:'/patient/test-results',icon:'⌁'}];if(this.role==='doctor')return[{label:'Dashboard',path:'/doctor/dashboard',icon:'⌂'},{label:'Patients',path:'/doctor/patients',icon:'👥'},{label:'Appointments',path:'/doctor/appointments',icon:'▣'},{label:'Medical Records',path:'/doctor/medical-records',icon:'▤'},{label:'Prescriptions',path:'/doctor/prescriptions',icon:'Rx'},{label:'CPOE',path:'/doctor/cpoe',icon:'⌁'},{label:'Test Results',path:'/doctor/test-results',icon:'◫'},{label:'Consultation',path:'/doctor/consultation',icon:'✚'}];return[{label:'Dashboard',path:'/admin/dashboard',icon:'⌂'},{label:'Patients',path:'/admin/patients',icon:'👥'},{label:'Doctors',path:'/admin/doctors',icon:'⚕'},{label:'Users',path:'/admin/users',icon:'◉'},{label:'Appointments',path:'/admin/appointments',icon:'▣'},{label:'System Management',path:'/admin/system',icon:'⚙'}]}
  refresh(){this.patients=this.s.patients();this.doctors=this.s.doctors();this.appointments=this.s.appointments();this.prescriptions=this.s.prescriptions();this.records=this.s.records();this.orders=this.s.orders();this.results=this.s.results();if(this.role==='patient'){const p=this.currentPatient();if(p)this.profileForm.patchValue(p);if(this.doctors[0]&&!this.appointmentForm.value.doctorId)this.appointmentForm.patchValue({doctorId:this.doctors[0].id});}if(this.role==='doctor'){const saved=localStorage.getItem('cc_selected_appointment');if(saved){const a=this.appointments.find(x=>x.id===saved);if(a)this.consultPatient=this.patients.find(p=>p.id===a.patientId)||null;}}}
  currentPatient(){return this.patients.find(p=>p.id===this.auth.user()?.id)}
  get myAppointments(){return this.appointments.filter(a=>a.patientId===this.auth.user()?.id)}
  get doctorAppointments(){return this.appointments.filter(a=>a.doctorId===this.auth.user()?.id)}
  get myPrescriptions(){return this.prescriptions.filter(x=>x.patientId===this.auth.user()?.id)}
  get visibleRecords(){return this.role==='patient'?this.records.filter(x=>x.patientId===this.auth.user()?.id):this.records}
  get visibleResults(){return this.role==='patient'?this.results.filter(x=>x.patientId===this.auth.user()?.id):this.results}
  get filteredPatients(){const q=this.search.toLowerCase();return this.patients.filter(p=>`${p.name} ${p.email} ${p.phone} ${p.id}`.toLowerCase().includes(q))}
  get selectedDoctor(){return ()=>this.doctors.find(d=>d.id===this.appointmentForm.value.doctorId)}
  get stats(){if(this.role==='patient')return[{icon:'◷',label:'Upcoming Appointments',value:this.myAppointments.filter(a=>!['Completed','Cancelled'].includes(a.status)).length},{icon:'Rx',label:'Active Prescriptions',value:this.myPrescriptions.length},{icon:'⌁',label:'Test Results',value:this.visibleResults.length},{icon:'▤',label:'Medical Records',value:this.visibleRecords.length}];if(this.role==='doctor')return[{icon:'👥',label:'Total Patients',value:this.patients.length},{icon:'◷',label:"Today's Appointments",value:this.doctorAppointments.filter(a=>a.date===this.today()).length},{icon:'!',label:'Pending Appointments',value:this.doctorAppointments.filter(a=>a.status==='Pending').length},{icon:'✓',label:'Completed Consultations',value:this.records.filter(r=>r.doctorId===this.auth.user()?.id).length}];return[{icon:'👥',label:'Total Patients',value:this.patients.length},{icon:'⚕',label:'Total Doctors',value:this.doctors.length},{icon:'◉',label:'Total Users',value:this.s.users().length},{icon:'◷',label:'Total Appointments',value:this.appointments.length}]}
  get adminCards(){return[{label:'Total Patients',value:this.patients.length},{label:'Total Doctors',value:this.doctors.length},{label:'Total Users',value:this.s.users().length},{label:'Total Appointments',value:this.appointments.length},{label:'Active Users',value:this.s.users().filter(x=>x.active).length},{label:'Inactive Users',value:this.s.users().filter(x=>!x.active).length}]}
  go(p:string){this.router.navigateByUrl(`/${this.role}/${p}`)}
  age(d:string){if(!d)return '-';const b=new Date(d),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a}
  lastVisit(id:string){const r=this.records.filter(x=>x.patientId===id).sort((a,b)=>b.date.localeCompare(a.date))[0];return r?.date||'—'}
  saveProfile(){const p=this.currentPatient();if(!p||this.profileForm.invalid)return;Object.assign(p,this.profileForm.getRawValue());this.s.savePatients(this.patients);const users=this.s.users().map(u=>u.id===p.id?{...u,name:p.name,email:p.email,phone:p.phone}:u);this.s.saveUsers(users);this.auth.syncSession();this.notify('Profile updated');}
  bookAppointment(){if(this.appointmentForm.invalid)return;const v=this.appointmentForm.getRawValue(),d=this.doctors.find(x=>x.id===v.doctorId),p=this.currentPatient();if(!d||!p)return;this.appointments.unshift({id:'apt-'+Date.now(),patientId:p.id,doctorId:d.id,patientName:p.name,doctorName:d.name,specialization:d.specialization,date:v.date!,time:v.time!,reason:v.reason!,status:'Pending'});this.s.saveAppointments(this.appointments);this.appointmentForm.patchValue({date:'',time:'',reason:''});this.notify('Appointment booked successfully');this.refresh();}
  openConsult(a:Appointment){localStorage.setItem('cc_selected_appointment',a.id);this.router.navigateByUrl('/doctor/consultation')}
  startPatientConsultation(p:Patient){const a=this.doctorAppointments.find(x=>x.patientId===p.id&&!['Completed','Cancelled'].includes(x.status));if(a)this.openConsult(a);else{localStorage.removeItem('cc_selected_appointment');this.consultPatient=p;this.selectedPatient=null;}}
  saveConsultation(){if(this.consultForm.invalid||!this.consultPatient)return;const v=this.consultForm.getRawValue();const rec:MedicalRecord={id:'rec-'+Date.now(),patientId:this.consultPatient.id,doctorId:this.auth.user()!.id,doctorName:this.auth.user()!.name,date:this.today(),symptoms:v.symptoms!,diagnosis:v.diagnosis!,observations:v.observations||'',clinicalNotes:v.clinicalNotes||'',treatmentPlan:v.treatmentPlan||'',suggestions:v.suggestions||'',precautions:v.precautions||'',followUp:v.followUp||''};this.records.unshift(rec);this.s.saveRecords(this.records);const selected=localStorage.getItem('cc_selected_appointment');if(selected){this.appointments=this.appointments.map(a=>a.id===selected?{...a,status:'Completed'}:a);this.s.saveAppointments(this.appointments);localStorage.removeItem('cc_selected_appointment');}this.notify('Consultation saved');this.consultForm.reset();}
  addMedicine(){if(this.medForm.invalid)return;this.cart.push(this.medForm.getRawValue() as Medication);this.medForm.reset();}
  removeMedicine(i:number){this.cart.splice(i,1)}
  savePrescription(){const p=this.patients.find(x=>x.id===this.rxPatientId)||this.patients[0];if(!p||!this.cart.length)return;const rx:Prescription={id:'rx-'+Date.now(),patientId:p.id,doctorId:this.auth.user()!.id,doctorName:this.auth.user()!.name,date:this.today(),medicines:[...this.cart]};this.prescriptions.unshift(rx);this.s.savePrescriptions(this.prescriptions);this.cart=[];this.notify('Prescription created');this.refresh();}
  addOrder(){if(this.orderForm.invalid)return;const v=this.orderForm.getRawValue(),p=this.patients.find(x=>x.id===v.patientId);if(!p)return;this.orders.unshift({id:'ord-'+Date.now(),patientId:p.id,doctorId:this.auth.user()!.id,patientName:p.name,testType:v.testType!,orderDate:v.orderDate!,remarks:v.remarks||'',priority:v.priority as 'Normal'|'Urgent',status:'Ordered'});this.s.saveOrders(this.orders);this.notify('Test order created');this.orderForm.reset({orderDate:this.today(),priority:'Normal'});}
  addResult(){if(this.resultForm.invalid)return;const v=this.resultForm.getRawValue(),p=this.patients.find(x=>x.id===v.patientId);if(!p)return;this.results.unshift({id:'res-'+Date.now(),patientId:p.id,doctorId:this.auth.user()!.id,patientName:p.name,testName:v.testName!,testDate:v.testDate!,result:v.result!,doctor:this.auth.user()!.name,remarks:v.remarks||'',status:v.status!});this.s.saveResults(this.results);this.notify('Test result added');this.resultForm.reset({testDate:this.today(),status:'Completed'});this.refresh();}
  viewPatient(p:Patient){this.selectedPatient=p}
  goPatientRecords(p:Patient){this.selectedPatient=null;this.search=p.name;this.router.navigateByUrl('/doctor/medical-records')}
  createDoctor(){if(this.role!=='admin'||this.doctorForm.invalid||this.doctorSubmitting)return;this.doctorSubmitting=true;const v=this.doctorForm.getRawValue();const d:User={id:'d-'+Date.now(),name:v.name!,email:v.email!,username:v.username||undefined,password:v.password!,role:'doctor',active:true,phone:v.phone||''};(d as any).specialization=v.specialization!;this.s.registerDoctor(d).subscribe({next:()=>{this.doctorSubmitting=false;this.notify('Doctor account created successfully');this.doctorForm.reset();this.refresh();},error:(e:any)=>{this.doctorSubmitting=false;this.notify(e?.error?.message||'Could not create doctor account');}});}
  adminList(){if(this.page==='patients')return this.s.users().filter(u=>u.role==='patient');if(this.page==='doctors')return this.s.users().filter(u=>u.role==='doctor');return this.s.users()}
  doctorSpec(id:string){return this.doctors.find(d=>d.id===id)?.specialization||'—'}
  toggleUser(u:User){if(u.id===this.auth.user()?.id){this.notify('You cannot deactivate your own account');return}if(!confirm(`${u.active?'Deactivate':'Activate'} ${u.name}?`))return;const users=this.s.users().map(x=>x.id===u.id?{...x,active:!x.active}:x);this.s.saveUsers(users);this.notify('User status changed');this.refresh();}
  notify(msg:string){this.toast=msg;setTimeout(()=>this.toast='',2500)}
}
